/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as GuardRouteImport } from './routes/guard'
import { Route as HygieneRouteImport } from './routes/hygiene'
import { Route as IntrusionRouteImport } from './routes/intrusion'
import { Route as PlatesRouteImport } from './routes/plates'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SupportRouteImport } from './routes/support'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardRoute = GuardRouteImport.update({
  id: '/guard',
  path: '/guard',
  getParentRoute: () => rootRouteImport,
} as any)
const HygieneRoute = HygieneRouteImport.update({
  id: '/hygiene',
  path: '/hygiene',
  getParentRoute: () => rootRouteImport,
} as any)
const IntrusionRoute = IntrusionRouteImport.update({
  id: '/intrusion',
  path: '/intrusion',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatesRoute = PlatesRouteImport.update({
  id: '/plates',
  path: '/plates',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/guard': typeof GuardRoute
  '/hygiene': typeof HygieneRoute
  '/intrusion': typeof IntrusionRoute
  '/plates': typeof PlatesRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/guard': typeof GuardRoute
  '/hygiene': typeof HygieneRoute
  '/intrusion': typeof IntrusionRoute
  '/plates': typeof PlatesRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/guard': typeof GuardRoute
  '/hygiene': typeof HygieneRoute
  '/intrusion': typeof IntrusionRoute
  '/plates': typeof PlatesRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance'
    | '/guard'
    | '/hygiene'
    | '/intrusion'
    | '/plates'
    | '/settings'
    | '/support'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendance'
    | '/guard'
    | '/hygiene'
    | '/intrusion'
    | '/plates'
    | '/settings'
    | '/support'
  id:
    | '__root__'
    | '/'
    | '/attendance'
    | '/guard'
    | '/hygiene'
    | '/intrusion'
    | '/plates'
    | '/settings'
    | '/support'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttendanceRoute: typeof AttendanceRoute
  GuardRoute: typeof GuardRoute
  HygieneRoute: typeof HygieneRoute
  IntrusionRoute: typeof IntrusionRoute
  PlatesRoute: typeof PlatesRoute
  SettingsRoute: typeof SettingsRoute
  SupportRoute: typeof SupportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guard': {
      id: '/guard'
      path: '/guard'
      fullPath: '/guard'
      preLoaderRoute: typeof GuardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hygiene': {
      id: '/hygiene'
      path: '/hygiene'
      fullPath: '/hygiene'
      preLoaderRoute: typeof HygieneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intrusion': {
      id: '/intrusion'
      path: '/intrusion'
      fullPath: '/intrusion'
      preLoaderRoute: typeof IntrusionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plates': {
      id: '/plates'
      path: '/plates'
      fullPath: '/plates'
      preLoaderRoute: typeof PlatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttendanceRoute: AttendanceRoute,
  GuardRoute: GuardRoute,
  HygieneRoute: HygieneRoute,
  IntrusionRoute: IntrusionRoute,
  PlatesRoute: PlatesRoute,
  SettingsRoute: SettingsRoute,
  SupportRoute: SupportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
